# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_hike_app', '0002_auto_20190725_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
