# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_hike_app', '0003_trip_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hikers',
            field=models.ManyToManyField(related_name='trips', to='take_a_hike_app.User'),
        ),
    ]
