# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_hike_app', '0004_auto_20190725_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='hikers',
            new_name='attending',
        ),
    ]
