# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_hike_app', '0005_auto_20190725_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='attending',
            new_name='users',
        ),
    ]
