# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-25 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_a_hike_app', '0006_auto_20190725_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_list', to='take_a_hike_app.User')),
            ],
        ),
    ]
